version: "3.7"

services:

  webserver-proxy:
    build: ./webserver-proxy
    image: ${NAMESPACE}:webserver-proxy
    container_name: ${NAMESPACE}_webserver-proxy
    depends_on:
    - webserver
    ports:
    - 80:80
    - 443:443

  webserver:
    build: ./webserver
    container_name: ${NAMESPACE}_webserver
    image: ${NAMESPACE}:webserver
    links:
    - php
    working_dir: ${WORKDIR_SERVER}
    expose:
    - 80
    volumes:
    - ../${WORKDIR}:${WORKDIR_SERVER}:delegated

  php:
    build:
      context: ./php/${PHP_VERSION}
    container_name: ${NAMESPACE}_php
    image: ${NAMESPACE}:php
    working_dir: ${WORKDIR_SERVER}
    depends_on:
    - database
    - mailhog
    ports:
    - 9000:9000
    volumes:
    - ../${WORKDIR}:${WORKDIR_SERVER}:delegated

  database:
    build: ./database
    container_name: ${NAMESPACE}_database
    image: ${NAMESPACE}:database
    #    expose:
    #    - 3306
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
    - ./database/inital-import:/docker-entrypoint-initdb.d:rw

  redis:
    image: redis:alpine
    container_name: ${NAMESPACE}_redis
    expose:
    - 6379
    sysctls:
      net.core.somaxconn: '511'

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${NAMESPACE}_mailhog
    expose:
    - 1025
    ports:
    - 8025:8025